# This is a basic workflow to help you get started with Actions
name: CI For Android Build

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Setup ionic Angular
        run: npm install -g @ionic/angular@latest
        
      - name: Setup Angular Cli
        run: npm install -g @angular/cli
          
      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install
        
      - name: Get Gradle Version
        run: gradle --version
        
      - name: ng cmd
        run: ng add @ionic/angular
                
      - name: Build ng app
        run: ng build --prod
         
      - name: Add Android platform
        run: ionic cordova platform add android@latest

      - name: Build Android Dev APK
        run: ionic capacitor build android

      - name: Build Android Release APK
        run: ionic cordova build android --release --prod

      - name: Generate the Android App Bundle
#         working-directory: ./platforms/android/
        working-directory: ./android/
        run: ./gradlew assembleDebug && ./gradlew assembleRelease

      - name: Upload dev APK
        uses: actions/upload-artifact@v2
        with:
          name: temp-artifact
          path: ./android/app/build/outputs/
                    
      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload release bundle
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: ./android/app/build/outputs/bundle/release/app.aab
